github:
  user_or_org: cctbx
  repo_name: nightly-feedstock
  branch_name: main
  tooling_branch_name: main
channels:
  targets:
    - [cctbx-nightly, main]

azure:
  user_or_org: cctbx-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
upload_on_branch: master
# build_with_mambabuild: False
test: native
